### ISSUE TITLE
htmx@2 issue

### ISSUE THREAD

**Issue by imbolc** [KatrinaKitten/htmx-template#1]
I found an issue trying to use the extension with the new version of htmx: https://github.com/bigskysoftware/htmx/discussions/2546

**Comment by kgscialdone** [comment]
This is caused by the default value of the `selfRequestsOnly` config parameter changing from `false` to `true` in 2.x. The fact that the extension works in the first place is a "bug" and would break if the config is changed even on 1.x.

Since truly fixing this would require changing the extension's public interface, I'm marking as won't fix for now, I may reconsider if more significant changes are needed in the future.
